// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoManager_hamdi.Models.RestosModel;

#nullable disable

namespace RestoManager_hamdi.Migrations
{
    [DbContext(typeof(RestosDbContext))]
    [Migration("20230507103258_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Avis", b =>
                {
                    b.Property<int>("CodeAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeAvis"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LeRestoCodeResto")
                        .HasColumnType("int");

                    b.Property<string>("NomPersonne")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Note")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("NumResto")
                        .HasColumnType("int");

                    b.HasKey("CodeAvis");

                    b.HasIndex("LeRestoCodeResto");

                    b.ToTable("TAvis", "admin");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Proprietaire", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailProp");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GsmProp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NomProp");

                    b.HasKey("Numero");

                    b.ToTable("TProprietaire", "resto");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Restaurant", b =>
                {
                    b.Property<int>("CodeResto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeResto"));

                    b.Property<string>("NomResto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumProp")
                        .HasColumnType("int");

                    b.Property<string>("Specialiste")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tunisienne")
                        .HasColumnName("SpecResto");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("TelResto");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VilleResto");

                    b.HasKey("CodeResto");

                    b.HasIndex("NumProp");

                    b.ToTable("TRestaurant", "resto");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Avis", b =>
                {
                    b.HasOne("RestoManager_hamdi.Models.RestosModel.Restaurant", "LeResto")
                        .WithMany("LesAvis")
                        .HasForeignKey("LeRestoCodeResto");

                    b.Navigation("LeResto");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Restaurant", b =>
                {
                    b.HasOne("RestoManager_hamdi.Models.RestosModel.Proprietaire", "LeProprio")
                        .WithMany("LesRestos")
                        .HasForeignKey("NumProp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Proprio_Restos");

                    b.Navigation("LeProprio");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Proprietaire", b =>
                {
                    b.Navigation("LesRestos");
                });

            modelBuilder.Entity("RestoManager_hamdi.Models.RestosModel.Restaurant", b =>
                {
                    b.Navigation("LesAvis");
                });
#pragma warning restore 612, 618
        }
    }
}
